### ISSUE TITLE
ReferenceError: pasrer is not defined

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [jithin-zachariah/gherkin-parse#1]
I'm getting the following error

```
const jsonObject = pasrer.convertFeatureFileToJSON("./sample.feature");
                   ^

ReferenceError: pasrer is not defined
```

**Comment by tarkers** [comment]
seems it is  a typo , i change it to parser and it works

**Comment by jithin-zachariah** [comment]
@tarkers and @UnnikrishnanBhargavakurup thank you for pointing it out. I have updated the readme and closing this issue.
